# Generated by Django 3.2.25 on 2024-09-04 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('input_day', models.DateField(default=datetime.date.today)),
                ('enter_day', models.DateField()),
                ('exit_day', models.DateField()),
                ('training', models.IntegerField(choices=[(1, '14日'), (2, '21日'), (3, '40日'), (4, 'その他')])),
                ('participation_cost_submit_or_not', models.IntegerField(choices=[(1, '完納'), (2, '未納')])),
                ('progress_state', models.IntegerField(choices=[(1, '準備中'), (2, '修練中'), (3, '退所'), (4, '短期滞在'), (5, '前泊・延泊')])),
            ],
        ),
    ]
