# Generated by Django 3.2.25 on 2024-09-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='extention_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='members',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='input_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='progress_state',
            field=models.IntegerField(choices=[(1, '準備中'), (2, '修練中'), (3, '退所'), (4, '短期滞在'), (5, '前泊・延泊')], default=1),
        ),
    ]
